name: negosmint_wallet
description: NegosMint Wallet — a premium non-custodial crypto wallet.
publish_to: "none"
version: 0.2.2+4

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^11.2.0
  wallet: ^0.0.18
  qr_flutter: ^4.1.0
  web3dart: ^3.0.3
  http: ^1.5.0
  local_auth: ^2.3.0
  app_links: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
